version: "3.9"

services:
  usuarios:
    build: ./usuarios_api
    ports:
      - "5001:5001"

  tareas:
    build: ./tareas_api
    ports:
      - "5002:5002"
    depends_on:
      - usuarios

  notificaciones:
    build: ./notificaciones_api
    ports:
      - "5003:5003"
    depends_on:
      - usuarios
      - tareas

  frontend:
    build: ./poke-app
    ports:
      - "8080:80"
    depends_on:
      - usuarios
      - tareas
